### ISSUE TITLE
Umbrellas dont use durability

### ISSUE THREAD

**Issue by Diego13303** [PneumonoIsNotAvailable/Umbrellas#5]
I´m using the latest version of the mod (v1.1.0+1.20.1) and Umbrellas are not using up any durability even after standing under the rain for a couple minutes

**Comment by PneumonoIsNotAvailable** [comment]
Hi, this is working as intended- for now at least.
I originally planned for umbrellas to use durability, but whenever the item NBT data changes the umbrella's position in first-person does that little bounce that items do when you switch from holding one to holding another. Since the umbrella was constantly doing this, it looked absolutely terrible, and I couldn't find a way to disable the animation so I just removed durability for the time being.
I might try and re-add durability, but I have no idea how to get rid of the animation, and I've been having a bit of a motivation drought for quite a while, so no promises on that being soon.
