### ISSUE TITLE
Requesting Integration with Scorchful and Frostiful

### ISSUE THREAD

**Issue by JasdanVM** [PneumonoIsNotAvailable/Umbrellas#7]
It'd be great if umbrellas protected you from temperature shifts in those mods.
Or do they do it already?

**Comment by PneumonoIsNotAvailable** [comment]
It _should_ block any checks for skylight, so if the mods make you colder in snow or warmer in the sun (which I'm assuming they do) then you should be protected from that. I won't make Umbrellas protect you from other heat/cold sources, since they don't cover you up or anything, and so I don't think it would really make sense.
